### ISSUE TITLE
Integration in Crowdin is missing

### ISSUE THREAD

**Issue by prathers** [franzholz/tcpdfbill_tt_products#1]
The integration to the repository is missing in Crowdin: https://crowdin.com/project/typo3-extension-tcpdfbillttpro/apps

**Comment by franzholz** [comment]
When will Crowdin translations work? I could not get it yet running with tt_products,.

**Comment by prathers** [comment]
Please have a look here: https://support.crowdin.com/github-integration/

**Comment by franzholz** [comment]
I have followed all steps successfully for tt_products. But the translations do not work.

**Comment by prathers** [comment]
Can you explain in more details, how the translation do not work?

**Comment by franzholz** [comment]
When I download the German translations in the TYPO3 backend, then the language files get stored into the folder typo3conf/l10n/de/tt_products/master for tt_products.
But the correct place is here:

**Comment by franzholz** [comment]
tt_products still does not work. I have sent you more details via Crowdin message.
